import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

function TopNav() {
  return (
    <nav  className="flex w-full items-center justify-between border-b p-4 text-xl font-semibold">
      <div>
        Gallery
      </div>
      <div>
        Sign In
      </div>
    </nav>
  )
}



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col gap-4`}

      >
        <TopNav />
        {children}
      </body>
    </html>
  );
}
